<a href="https://colab.research.google.com/github/PRASADPRATYUSH2323/PRASADPRATYUSH2323/blob/main/Assignment_3_Dis_similarity_measure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# importing libraries, number of dimensions and points

In [ ]:
# importing libraries
import numpy as np
from numpy import random
import pandas as pd
from matplotlib import pyplot as plt
import matplotlib.ticker as ticker

In [ ]:
# taking in the number of points and dimensions
a=int(input('type the number of points:'))
b=int(input('type the number of dimensions:'))
print(a)
print(b)

type the number of points:5
type the number of dimensions:10
5
10


In [ ]:
# creating random points
p=[]
for i in range(0,a):
    w=np.random.rand(b)
    w=(2*w)-1
    p.append(w)
print(p)

[array([ 0.27203533, -0.39490652, -0.87024963,  0.28424822,  0.73970226,
        0.63268467, -0.141347  ,  0.98966349,  0.36210857,  0.89006547]), array([ 0.16390878,  0.75377474, -0.17538592,  0.22510199,  0.27953381,
        0.77316589,  0.88889116,  0.49263352, -0.96813297, -0.69731799]), array([-0.20732552,  0.36093367, -0.52882761,  0.52462677, -0.90781252,
       -0.48639645, -0.64637229,  0.21767595, -0.52215716,  0.80983296]), array([ 0.17907259,  0.24417796, -0.19144662,  0.36698889, -0.89243223,
        0.6168611 ,  0.36270305, -0.21202317,  0.22720562,  0.69781398]), array([-0.51567844, -0.71909057, -0.48389382,  0.56367798, -0.6654938 ,
        0.85700884,  0.36984424, -0.19423666,  0.68096429,  0.64969027])]


# finding distance from origin, angle of every point wrt each axis, angle between 2 points

In [ ]:
# distance from origin

def dist(i):
    d=0
    for j in i:
        d+=j**2
    di=d**.5
    dis.append(di)
        
dis=[]
for i in p:
    dist(i)

dis=np.array(dis)

print(dis)

[1.98451181 1.95160122 1.78395948 1.46800869 1.89012439]


In [ ]:
# angle with respect to each dimension

def angle(i,p):
    for j in range(0,b):
        v1=np.zeros(b)
        v1[j]=1
        cost=np.dot(v1,p)/(dis[i]**.5)
        t=np.arccos(cost)*180/np.pi
        angles.append(t)

angles=[]

for i in range(0,a):
    angle(i,p[i])
    
angles=np.array(angles)    
angles=angles.reshape(a,b)
print(angles)

[[ 78.86582754 106.27981946 128.15245352  78.35912793  58.32599464
   63.31288978  95.75855877  45.37020265  75.10510694  50.81528617]
 [ 83.26200305  57.34577679  97.2122259   80.72734955  78.45741654
   56.39608829  50.48449587  69.35128235 133.86884729 119.94410373]
 [ 98.92981683  74.32199648 113.32417143  66.87192603 132.81854216
  111.35618903 118.94295379  80.62044766 113.01292529  52.67600503]
 [ 81.50073493  78.37349022  99.0913832   72.36857992 137.43960207
   59.39454172  72.58111736 100.0782116   79.1917303   54.8346877 ]
 [112.0297846  121.53667343 110.60781857  65.79504523 118.95087704
   51.43795908  74.39444221  98.12202141  60.30965175  61.79910183]]


In [ ]:
# angle betweem every point

def pointangle(q,r,i,j):
    if i==j:
        cost=1
    else:
        cost=np.dot(q,r)/((dis[i]*dis[j])**.5)
    pointangles.append(cost)

pointangles=[]
for i in range(0,a):
    for j in range(0,a):
        pointangle(p[i],p[j],i,j)
        
pointangles=np.array(pointangles)   
pointangles=pointangles.reshape(a,a)
pointangles=(np.arccos(pointangles))*180/np.pi
print(pointangles)        

[[  0.          88.53989153  81.75986076  76.59748503  45.5896835 ]
 [ 88.53989153   0.         112.27984739  87.68214363 115.19022043]
 [ 81.75986076 112.27984739   0.          50.89237865  74.99181426]
 [ 76.59748503  87.68214363  50.89237865   0.                  nan]
 [ 45.5896835  115.19022043  74.99181426          nan   0.        ]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:17: RuntimeWarning: invalid value encountered in arccos


# dissimilarity between 2 points

In [ ]:
# checking dissimilarity between 2 points
def dissimilarity2(p,i,j,v1):
    
    # finging the hamming distance
    distance_hamming=0
    for k in range(0,b):
        if p[k]==0:
            x=0
        else:
            x=1
        distance_hamming+=x
    hamming2.append(distance_hamming)
    
    # lebesgue supremum norm
    distance_supremum=max(p)
    supremum2.append(distance_supremum) 
    
    # lebesgue euclidean norm
    x=0
    for k in range(0,b):
        x+=p[k]**2
    X=x**.5
    euclidean2.append(X)
    
    # lebesgue manhattan norm
    x=0
    for k in range(0,b):
        x+=(p[k]**2)**.5
    manhattan2.append(x)
    
    # lebesgue infimum norm
    distance_infimum=min(p)
    infimum2.append(distance_infimum)
    
    # minkowski norm
    x=0
    for k in range(0,b):
        x+=p[k]**b
    X=x**(1/b)
    minkowski2.append(X)
    
    # matrix hilbert-schmidt, euclidean, diagonal norms
    rows, cols = (b,b)
    sum=0
    for k in p:
        sum+=k
    sum=sum/b
    
    A_hilbertschmidt = [[1]*cols]*rows
    A_euclidean=np.identity(b,dtype='float')
    A_diagonal=np.diag(v1)
    
    B_h=np.dot(p,A_hilbertschmidt)
    B_e=np.dot(p,A_euclidean)
    B_d=np.dot(p,A_diagonal)
    
    pt=np.transpose(p)
    
    C_h=np.dot(B_h,pt)
    C_e=np.dot(B_e,pt)
    C_d=np.dot(B_d,pt)
    
    matrix_euclidean2.append(C_e**.5)
    matrix_hilbertschmidt2.append(C_h**.5)
    matrix_diagonal2.append(C_d**.5)
    
matrix_euclidean2=     []
matrix_hilbertschmidt2=[]
matrix_diagonal2=      []
matrix_mahalanobis2=   []
minkowski2=            []
infimum2=              []
manhattan2=            []
euclidean2=            []
supremum2=             []
hamming2=              []
    
v1=np.random.rand(b)
for i in range(0,a):
    for j in range(0,a):
        dissimilarity2(p[i]-p[j],i,j,v1)
        
matrix_euclidean2=np.array(matrix_euclidean2)
matrix_hilbertschmidt2=np.array(matrix_hilbertschmidt2)
matrix_diagonal2=np.array(matrix_diagonal2)
minkowski2=np.array(minkowski2)
infimum2=np.array(infimum2)
manhattan2=np.array(manhattan2)
euclidean2=np.array(euclidean2)
supremum2=np.array(supremum2)
hamming2=np.array(hamming2)

matrix_euclidean2=matrix_euclidean2.reshape(a,a)
matrix_hilbertschmidt2=matrix_hilbertschmidt2.reshape(a,a)
matrix_diagonal2=matrix_diagonal2.reshape(a,a)
minkowski2=minkowski2.reshape(a,a)
infimum2=infimum2.reshape(a,a)
manhattan2=manhattan2.reshape(a,a)
euclidean2=euclidean2.reshape(a,a)
supremum2=supremum2.reshape(a,a)
hamming2=hamming2.reshape(a,a)

print(matrix_euclidean2)
print(matrix_hilbertschmidt2)
print(matrix_diagonal2)
print(minkowski2)
print(infimum2)
print(manhattan2)
print(euclidean2)
print(supremum2)
print(hamming2)

[[0.         2.76527433 2.56543524 2.30262474 2.19094104]
 [2.76527433 0.         2.89932711 2.41389453 3.00270578]
 [2.56543524 2.89932711 0.         1.81548671 2.4091594 ]
 [2.30262474 2.41389453 1.81548671 0.         1.36107656]
 [2.19094104 3.00270578 2.4091594  1.36107656 0.        ]]
[[0.         1.02783184 4.14982704 1.36508368 2.22121251]
 [1.02783184 0.         3.1219952  0.33725184 1.19338067]
 [4.14982704 3.1219952  0.         2.78474336 1.92861453]
 [1.36508368 0.33725184 2.78474336 0.         0.85612883]
 [2.22121251 1.19338067 1.92861453 0.85612883 0.        ]]
[[0.         1.97461558 1.82322919 1.85335971 1.69388727]
 [1.97461558 0.         2.22114033 1.77526835 1.91142666]
 [1.82322919 2.22114033 0.         1.33334707 1.57685779]
 [1.85335971 1.77526835 1.33334707 0.         0.66573751]
 [1.69388727 1.91142666 1.57685779 0.66573751 0.        ]]
[[0.         1.6197554  1.65139894 1.63965719 1.42904899]
 [1.6197554  0.         1.64919854 1.44177153 1.71261935]
 [1.6513989

# dis-similarity of 1 point

In [ ]:
def dissimilarity1(p,i,j,v1):
    
    distance_hamming=0
    for k in range(0,b):
        if p[k]==0:
            x=0
        else:
            x=1
        distance_hamming+=x
    hamming1.append(distance_hamming)
    
    distance_supremum=max(p)
    supremum1.append(distance_supremum) 
    
    x=0
    for k in range(0,b):
        x+=p[k]**2
    X=x**.5
    euclidean1.append(X)
    
    x=0
    for k in range(0,b):
        x+=(p[k]**2)**.5
    manhattan1.append(x)
    
    distance_infimum=min(p)
    infimum1.append(distance_infimum)
    
    x=0
    for k in range(0,b):
        x+=p[k]**b
    X=x**(1/b)
    minkowski1.append(X)
    
    rows, cols = (b,b)
    sum=0
    for k in p:
        sum+=k
    sum=sum/b
    
    A_hilbertschmidt = [[1]*cols]*rows
    A_euclidean=np.identity(b,dtype='float')
    A_diagonal=np.diag(v1)
    
    B_h=np.dot(p,A_hilbertschmidt)
    B_e=np.dot(p,A_euclidean)
    B_d=np.dot(p,A_diagonal)
    
    pt=np.transpose(p)
    
    C_h=np.dot(B_h,pt)
    C_e=np.dot(B_e,pt)
    C_d=np.dot(B_d,pt)
    
    matrix_euclidean1.append(C_e**.5)
    matrix_hilbertschmidt1.append(C_h**.5)
    matrix_diagonal1.append(C_d**.5)
    
matrix_euclidean1=     []
matrix_hilbertschmidt1=[]
matrix_diagonal1=      []
matrix_mahalanobis1=   []
minkowski1=            []
infimum1=              []
manhattan1=            []
euclidean1=            []
supremum1=             []
hamming1=              []
    
v1=np.random.rand(b)
for i in range(0,a):
    dissimilarity1(p[i],i,j,v1)
        
matrix_euclidean1=np.array(matrix_euclidean1)
matrix_hilbertschmidt1=np.array(matrix_hilbertschmidt1)
matrix_diagonal1=np.array(matrix_diagonal1)
minkowski1=np.array(minkowski1)
infimum1=np.array(infimum1)
manhattan1=np.array(manhattan1)
euclidean1=np.array(euclidean1)
supremum1=np.array(supremum1)
hamming1=np.array(hamming1)

print(matrix_euclidean1)
print(matrix_hilbertschmidt1)
print(matrix_diagonal1)
print(minkowski1)
print(infimum1)
print(manhattan1)
print(euclidean1)
print(supremum1)
print(hamming1)

[1.98451181 1.95160122 1.78395948 1.46800869 1.89012439]
[2.76400485 1.73617301 1.38582219 1.39892117 0.54279234]
[1.06080964 1.35214277 1.1764775  0.97492714 1.28934532]
[1.04289386 1.01796436 0.93666135 0.90184298 0.888873  ]
[-0.87024963 -0.96813297 -0.90781252 -0.89243223 -0.71909057]
[5.57701115 5.41784677 5.21196091 3.99072521 5.69957891]
[1.98451181 1.95160122 1.78395948 1.46800869 1.89012439]
[0.98966349 0.88889116 0.80983296 0.69781398 0.85700884]
[10 10 10 10 10]


# similarity between 2 points

In [ ]:
# finding cosine2, overlap2, dice2, jaccard2 similarity between 2 points

def similarity2(r,s):
        
    sum_rs=0
    sum_rr=0
    sum_ss=0
    dis_rs=0
    
    for i in range(0,b):
        sum_rs+=(r[i]*s[i])
        sum_rr+=(r[i]*r[i])
        sum_ss+=(s[i]*s[i])
        dis_rs+=(s[i]-r[i])**2
    
    e=sum_rs/(sum_rr*sum_ss)**.5      
    f=sum_rs/min(sum_rr,sum_ss)
    g=2*sum_rs/(sum_rr+sum_ss)
    h=sum_rs/(sum_rr+sum_ss-sum_rs)
    
    cosine2.append(e)    # cosine similarity
    overlap2.append(f)   # overlap similarity
    dice2.append(g)      # dice similarity
    jaccard2.append(h)   # jaccard similarity
    
cosine2=[]
overlap2=[]
dice2=[]
jaccard2=[]

for i in range(0,a):
    for j in range(0,a):
        similarity2(p[i],p[j])

cosine2=np.array(cosine2)
overlap2=np.array(overlap2)
dice2=np.array(dice2)
jaccard2=np.array(jaccard2)

cosine2=cosine2.reshape(a,a)
overlap2=overlap2.reshape(a,a)
dice2=dice2.reshape(a,a)
jaccard2=jaccard2.reshape(a,a)
        
print(cosine2)
print(overlap2)
print(dice2)
print(jaccard2) 

# point to remember - dot product and cosine2 are the same thing

[[ 1.          0.01294771  0.07617184  0.13580153  0.36132409]
 [ 0.01294771  1.         -0.20318935  0.02389382 -0.22160841]
 [ 0.07617184 -0.20318935  1.          0.3897808   0.14102303]
 [ 0.13580153  0.02389382  0.3897808   1.          0.69828517]
 [ 0.36132409 -0.22160841  0.14102303  0.69828517  1.        ]]
[[ 1.          0.01316606  0.08473506  0.18358185  0.37936759]
 [ 0.01316606  1.         -0.2222834   0.03176494 -0.22881629]
 [ 0.08473506 -0.2222834   1.          0.47367101  0.14941543]
 [ 0.18358185  0.03176494  0.47367101  1.          0.89907223]
 [ 0.37936759 -0.22881629  0.14941543  0.89907223  1.        ]]
[[ 1.          0.0129459   0.07574159  0.12985594  0.36089551]
 [ 0.0129459   1.         -0.20237256  0.02295686 -0.22149494]
 [ 0.07574159 -0.20237256  1.          0.38249098  0.14078773]
 [ 0.12985594  0.02295686  0.38249098  1.          0.67656208]
 [ 0.36089551 -0.22149494  0.14078773  0.67656208  1.        ]]
[[ 1.          0.00651512  0.03936144  0.06943633  0