<a href="https://colab.research.google.com/github/PRASADPRATYUSH2323/PRASADPRATYUSH2323/blob/main/Assignment_2_Distance_and_angle_between_2_random_points_with_the_number_of_dimensions_taken_by_user.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Section 1 taking numbers between 0 and 1

In [ ]:
# importing the libraries
import numpy as np
from numpy import random
import pandas as pd
from matplotlib import pyplot as plt
import matplotlib.ticker as ticker

In [ ]:
# typing the number of inputs
n=int(input('type the number of entries :'))

type the number of entries :100


In [ ]:
# taking random data with the number of dimensions as the input take
a=np.random.rand(n,1)
b=np.random.rand(n,1)
print(a)
print()
print(b)

[[0.27393422]
 [0.19675116]
 [0.83210275]
 [0.76426037]
 [0.45625937]
 [0.75746851]
 [0.7403997 ]
 [0.93147384]
 [0.57213225]
 [0.94964806]
 [0.29837463]
 [0.2162795 ]
 [0.41855954]
 [0.54853641]
 [0.87933165]
 [0.76520452]
 [0.07733435]
 [0.10281328]
 [0.9157703 ]
 [0.86684635]
 [0.47351734]
 [0.62216195]
 [0.51756917]
 [0.83380013]
 [0.19098836]
 [0.26335469]
 [0.4654942 ]
 [0.81492788]
 [0.98964465]
 [0.7240924 ]
 [0.98959272]
 [0.65081488]
 [0.3974247 ]
 [0.6654817 ]
 [0.96981668]
 [0.20837453]
 [0.78826865]
 [0.66016863]
 [0.11492323]
 [0.40034216]
 [0.07247687]
 [0.4303913 ]
 [0.19068331]
 [0.98329718]
 [0.96525861]
 [0.63633176]
 [0.43382188]
 [0.22938412]
 [0.90276926]
 [0.06670485]
 [0.50329272]
 [0.82212521]
 [0.23491089]
 [0.22597726]
 [0.43372613]
 [0.85569599]
 [0.1228291 ]
 [0.75607236]
 [0.26071541]
 [0.20060008]
 [0.15906728]
 [0.35366771]
 [0.53945648]
 [0.86750436]
 [0.02104438]
 [0.48643386]
 [0.68094042]
 [0.21951116]
 [0.25493202]
 [0.70834087]
 [0.34222244]
 [0.03

In [ ]:
# distance of vector a and x from origin
ssa=0
ssb=0
ssab=0
for i in range(0,n):
    ssa+=((a[i])**2)
    ssb+=((b[i])**2)
    ssab+=((a[i])-(b[i]))**2
dist_ao=ssa**.5
dist_bo=ssb**.5
dist_ab=ssab**.5
print('distance of a from origin',dist_ao)
print('distance of b from origin',dist_bo)
print('distance of b from a',dist_ab)

distance of a from origin [5.73157015]
distance of b from origin [5.65056964]
distance of b from a [4.10283534]


In [ ]:
# finding dot product of both points
A=np.array(a)
B=np.array(b)
C=A*B
print(C)

[[0.22844511]
 [0.10187266]
 [0.56660453]
 [0.06274818]
 [0.08798728]
 [0.38931173]
 [0.72289296]
 [0.71738707]
 [0.27821654]
 [0.82325222]
 [0.11279093]
 [0.02746291]
 [0.19205359]
 [0.47559436]
 [0.35256623]
 [0.35412387]
 [0.01431117]
 [0.05749527]
 [0.09250141]
 [0.00371331]
 [0.14430812]
 [0.04455887]
 [0.33195349]
 [0.46057236]
 [0.09229295]
 [0.20668474]
 [0.24508115]
 [0.67169805]
 [0.3715427 ]
 [0.19338173]
 [0.90303558]
 [0.63411042]
 [0.17239861]
 [0.58959658]
 [0.19468405]
 [0.14549342]
 [0.49357794]
 [0.25974422]
 [0.0842738 ]
 [0.23822754]
 [0.01952426]
 [0.17686367]
 [0.18250746]
 [0.50400542]
 [0.55974392]
 [0.17506287]
 [0.31303767]
 [0.10885674]
 [0.17767942]
 [0.01264149]
 [0.04270641]
 [0.7017194 ]
 [0.17376881]
 [0.08722551]
 [0.24986939]
 [0.26460993]
 [0.1070633 ]
 [0.71575303]
 [0.2414425 ]
 [0.10254413]
 [0.02104746]
 [0.0576432 ]
 [0.02314786]
 [0.03313994]
 [0.00217918]
 [0.12203234]
 [0.65882907]
 [0.10401303]
 [0.25306188]
 [0.6885829 ]
 [0.20910802]
 [0.01

In [ ]:
# finding the sum of dot products 
sc=0
for i in C:
    sc+=i
print(sc)    

[23.97328794]


In [ ]:
# printing the cosine of angle
cost=sc/(dist_ao*dist_bo)
print(cost)

[0.74022161]


In [ ]:
# printing angle in degree and radians
print('angle in radians:',np.arccos(cost))
print('angle in degrees:',(np.arccos(cost))*180/np.pi)

angle in radians: [0.73739643]
angle in degrees: [42.24970355]


# Section 2 taking numbers between -1 and 1

In [ ]:
# importing the libraries
import numpy as np
from numpy import random
import pandas as pd
from matplotlib import pyplot as plt
import matplotlib.ticker as ticker

In [ ]:
# typing the number of inputs
n=int(input('type the number of entries :'))

type the number of entries :100


In [ ]:
# taking random data with the number of dimensions as the input take
a=np.random.rand(n,1)
b=np.random.rand(n,1)
a=(2*a)-1
b=(2*b)-1
print(a)
print()
print(b)

[[-0.02241646]
 [ 0.82695698]
 [ 0.115912  ]
 [-0.38115136]
 [ 0.70316878]
 [ 0.75609067]
 [-0.01822352]
 [ 0.84583907]
 [ 0.37949886]
 [ 0.43836134]
 [-0.02835387]
 [-0.70004831]
 [ 0.12287681]
 [-0.76890436]
 [ 0.57974424]
 [-0.19880217]
 [ 0.23411567]
 [ 0.15341247]
 [-0.35948825]
 [-0.53213593]
 [-0.84221434]
 [-0.60564067]
 [-0.08055302]
 [-0.37424227]
 [ 0.34478765]
 [-0.75489942]
 [-0.79370256]
 [ 0.05860561]
 [ 0.78253284]
 [ 0.51214464]
 [-0.264895  ]
 [-0.35790592]
 [ 0.8750038 ]
 [-0.70276803]
 [ 0.85846571]
 [ 0.98609864]
 [-0.60114276]
 [-0.91769301]
 [-0.49334343]
 [ 0.34964072]
 [-0.28627869]
 [ 0.67177632]
 [ 0.68215125]
 [ 0.61534725]
 [ 0.99100784]
 [ 0.30070572]
 [-0.83253918]
 [ 0.34187744]
 [ 0.66847357]
 [ 0.15470702]
 [-0.92988755]
 [ 0.41844048]
 [-0.05901792]
 [ 0.3743047 ]
 [-0.72378023]
 [ 0.47576305]
 [-0.8798598 ]
 [ 0.60365945]
 [ 0.54316067]
 [ 0.68423757]
 [ 0.84439285]
 [ 0.30450449]
 [ 0.58697921]
 [ 0.01415907]
 [ 0.02886653]
 [ 0.03795659]
 [-0.96738

In [ ]:
# distance of vector a and x from origin 
ssa=0
ssb=0
ssab=0
for i in range(0,n):
    ssa+=((a[i])**2)
    ssb+=((b[i])**2)
    ssab+=((a[i])-(b[i]))**2
dist_ao=ssa**.5
dist_bo=ssb**.5
dist_ab=ssab**.5
print('distance of a from origin',dist_ao)
print('distance of b from origin',dist_bo)
print('distance of b from a',dist_ab)

distance of a from origin [5.85555697]
distance of b from origin [5.88223631]
distance of b from a [7.81202831]


In [ ]:
# finding dot product of both points
A=np.array(a)
B=np.array(b)
C=A*B
print(C)

[[ 0.01781815]
 [ 0.71225276]
 [ 0.07463994]
 [ 0.27372691]
 [-0.42498185]
 [ 0.2360196 ]
 [ 0.00687595]
 [-0.47271962]
 [ 0.10459761]
 [ 0.32912083]
 [ 0.01737824]
 [-0.13719027]
 [ 0.07948163]
 [-0.48075584]
 [ 0.01423344]
 [-0.04144047]
 [ 0.12497822]
 [ 0.12640585]
 [ 0.32691558]
 [-0.28195584]
 [ 0.34143071]
 [-0.30907601]
 [-0.00431236]
 [ 0.11566616]
 [ 0.31763039]
 [-0.27805382]
 [ 0.58464892]
 [-0.04824514]
 [ 0.53331873]
 [-0.11808159]
 [ 0.21975096]
 [-0.27543618]
 [-0.33139641]
 [ 0.62910875]
 [ 0.53958015]
 [ 0.28636622]
 [ 0.58661171]
 [ 0.30023404]
 [ 0.00729057]
 [ 0.20389425]
 [-0.18185931]
 [-0.46852648]
 [-0.11038633]
 [ 0.5658862 ]
 [-0.15239781]
 [-0.19454661]
 [-0.634092  ]
 [ 0.07233081]
 [-0.47525382]
 [-0.09519456]
 [ 0.80021629]
 [ 0.2253008 ]
 [-0.04023809]
 [-0.02086741]
 [ 0.4288799 ]
 [ 0.2532898 ]
 [ 0.3416684 ]
 [ 0.19955635]
 [ 0.39838305]
 [-0.22970133]
 [ 0.57309993]
 [-0.19705318]
 [-0.41971185]
 [ 0.00524952]
 [-0.02697539]
 [-0.02932043]
 [-0.24166

In [ ]:
# finding the sum of dot products 
sc=0
for i in C:
    sc+=i
print(sc)    

[3.93023256]


In [ ]:
# printing the cosine of angle
cost=sc/(dist_ao*dist_bo)
print(cost)

[0.11410576]


In [ ]:
# printing angle in degree and radians
print('angle in radians:',np.arccos(cost))
print('angle in degrees:',(np.arccos(cost))*180/np.pi)

angle in radians: [1.45644149]
angle in degrees: [83.44795061]
